### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'database_dir'

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/seroba#14]
```
% seroba getPneumocat db

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==0.1.4', 'seroba')
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(script_code, namespace, namespace)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/seroba-0.1.4-py3.6.egg/EGG-INFO/scripts/seroba", line 86, in <module>
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/seroba-0.1.4-py3.6.egg/seroba/tasks/getPneumocat.py", line 6, in run
AttributeError: 'Namespace' object has no attribute 'database_dir'
```

**Comment by eppinglen** [comment]
Thank you for reporting. The error has been fixed

**Comment by tseemann** [comment]
I wasn't aware a database was included?

The docs seem to tell me about `getPneuomoCat` as the first thing.

How do we use it?
Could you add some example command lines and an example contigs file to run it on?

**Comment by eppinglen** [comment]
Since version 0.1.3 we includes an extended database with novel serotypes. 
(added serotypes: 6G, 6F, 11E, 10X, 39X and two NT references)
For a practical exercise with SeroBA, please have look here: https://github.com/sanger-pathogens/pathogen-informatics-training
