### ISSUE TITLE
pkg_resources.ResolutionError: No script named 'seroba'

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/seroba#22]
I reinstalled from git (`git clone seroba && cd seroba && python3 setup.py install`):

```
% seroba

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==0.1.5', 'seroba')
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 748, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/linuxbrew/.linuxbrew/opt/python3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1509, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'seroba'
```

**Comment by andrewjpage** [comment]
Starting from a blank linuxbrew system, these are the commands I ran which got seroba running:

```
docker pull linuxbrew/linuxbrew
docker run --rm -it linuxbrew/linuxbrew bash

brew tap homebrew/science
brew install python3 python 

echo 'PATH="/home/linuxbrew/.linuxbrew/opt/python/libexec/bin:$PATH"' >>~/.bash_profile
export PATH="/home/linuxbrew/.linuxbrew/opt/python/libexec/bin:$PATH"
echo 'import site; site.addsitedir("/home/linuxbrew/.linuxbrew/lib/python2.7/site-packages")' >> homebrew.pth

brew install bowtie2 kmc mummer cd-hit

git clone https://github.com/sanger-pathogens/ariba.git
cd ariba
export MPLBACKEND="agg"
pip3 install .

cd ~
git clone https://github.com/sanger-pathogens/seroba.git
cd seroba
pip3 install .
seroba
```
Its probably not the cleanest, but hope this helps.

**Comment by tseemann** [comment]
Why do I need `ariba` ?
And what is this magic `MPLBACKED="agg"` ?

**Comment by andrewjpage** [comment]
Ariba does the local assembly under the hood. The MPL environment stops
matplotlib demanding you are running X. So only needed for headless servers.
Andrew

On 16 Sep 2017 2:03 am, "Torsten Seemann" <notifications@github.com> wrote:

Why do I need ariba ?
And what is this magic MPLBACKED="agg" ?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/sanger-pathogens/seroba/issues/22#issuecomment-329934547>,
or mute the thread
