### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bhclement** [sanger-pathogens/seroba#35]
Hello, 
I install  seroba and download the database from PneumoCaT. But I am not able to create the database.
(py36)[ctsui@grl-salk Strep_sero]$ seroba createDBs pneumoDB 71 
Traceback (most recent call last):
  File "/home/ctsui/.conda/envs/py36/bin/seroba", line 86, in <module>
    args.func(args)
  File "/home/ctsui/.conda/envs/py36/lib/python3.6/site-packages/seroba/tasks/createDBs.py", line 10, in run
    ref_db.run()
  File "/home/ctsui/.conda/envs/py36/lib/python3.6/site-packages/seroba/ref_db_creator.py", line 237, in run
    os.makedirs(os.path.join(self.out_dir,'ariba_db'))
  File "/home/ctsui/.conda/envs/py36/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'pneumoDB/ariba_db'
(

Will appreciate for advice! Thanks,

Clement

**Comment by bhclement** [comment]
I have these files in pneumoDB dir

(py36)[ctsui@grl-salk Strep_sero]$ ls ./pneumoDB/
ariba_db  cd_cluster.tsv  cdhit_cluster  meta.tsv  reference.fasta  streptococcus-pneumoniae-ctvdb

shall I move the ariba_db to somewhere?
