### ISSUE TITLE
seroba stopping signal recieved 28

### ISSUE THREAD

**Issue by varunshamanna** [sanger-pathogens/seroba#45]
cluster detected 1 threads available to it
cluster reported completion
The following command failed with exit code 1
rm -rf /media/crlkims/Data_Vol_1/ROSE/Wghole_genome_sequencing_pneumoniae/RawData_385/ERR1638455/fastq_files/seroba_out/ref/ariba.tmp.1_w_k7u0/cluster

The output was:

rm: cannot remove '/media/crlkims/Data_Vol_1/ROSE/Wghole_genome_sequencing_pneumoniae/RawData_385/ERR1638455/fastq_files/seroba_out/ref/ariba.tmp.1_w_k7u0/cluster': Directory not empty

Stopping! Signal received: 28
Traceback (most recent call last):
  File "/home/crlkims/anaconda2/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==1.0.1', 'seroba')
  File "/home/crlkims/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/crlkims/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/crlkims/anaconda2/lib/python3.6/site-packages/seroba-1.0.1-py3.6.egg/EGG-INFO/scripts/seroba", line 86, in <module>
  File "/home/crlkims/anaconda2/lib/python3.6/site-packages/seroba-1.0.1-py3.6.egg/seroba/tasks/sero_run.py", line 19, in run
  File "/home/crlkims/anaconda2/lib/python3.6/site-packages/seroba-1.0.1-py3.6.egg/seroba/serotyping.py", line 480, in run
  File "/home/crlkims/anaconda2/lib/python3.6/site-packages/seroba-1.0.1-py3.6.egg/seroba/serotyping.py", line 94, in _run_ariba_on_cluster
  File "/home/crlkims/anaconda2/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'seroba_out/genes/assembled_genes.fa.gz'

I am gettig report.tsv but its not complete

**Comment by eppinglen** [comment]
looks like a problem with ARIBA. Which version of python are you using?

**Comment by tseemann** [comment]
@eppinglen the error messages have `python3.6` in them.
but they are using Ananconda2 ... i would move to `miniconda3`

**Comment by varunshamanna** [comment]
Yes i was using anaconda2, i moved to conda3 now working fine
