### ISSUE TITLE
"Bash Run_nucmer.sh" Error

### ISSUE THREAD

**Issue by abcdtree** [sanger-pathogens/seroba#48]
Dear Developer,

In what case will seroba run **run_nucmer.sh**? And where is this assembly file which rummer requires from **"/data/xxxxxxx/result/assemblies.fa"**

Do I need to provide assembly for seroba?

```WARNING: not enough proper read pairs (found 0) to determine insert size.
This probably means that very few reads were mapped at all. No local assemblies will be run
WARNING: not enough proper read pairs (found 0) to determine insert size.
This probably means that very few reads were mapped at all. No local assemblies will be run
The following command failed with exit code 255
bash run_nucmer.sh

The output was:

bash: warning: setlocale: LC_ALL: cannot change locale (en_US.utf8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = "en_US.utf8",
	LC_COLLATE = "C",
	LANG = "en_AU.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
1: PREPARING DATA
2,3: RUNNING mummer AND CREATING CLUSTERS
reading input file "p.ntref" of length 8097 
construct suffix tree for sequence of length 8097
(maximum reference length is 536870908)
(maximum query length is 4294967295)
CONSTRUCTIONTIME /usr/bin/mummer p.ntref 0.00
/usr/bin/mummer: cannot open file "/data/xxxxxxxx/result/assemblies.fa" or file "/data/xxxxxxx/result/assemblies.fa" is empty
ERROR: mummer and/or mgaps returned non-zero
ERROR: Could not parse delta file, p.delta
error no: 400
ERROR: Could not parse delta file, p.delta.filter
error no: 402
ERROR: Could not parse delta file, p.delta.filter
error no: 402

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pymummer/syscall.py", line 20, in run
    output = subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'bash run_nucmer.sh' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==1.0.1', 'seroba')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/seroba-1.0.1-py3.7.egg/EGG-INFO/scripts/seroba", line 86, in <module>
  File "/usr/local/lib/python3.7/dist-packages/seroba-1.0.1-py3.7.egg/seroba/tasks/sero_run.py", line 19, in run
  File "/usr/local/lib/python3.7/dist-packages/seroba-1.0.1-py3.7.egg/seroba/serotyping.py", line 481, in run
  File "/usr/local/lib/python3.7/dist-packages/seroba-1.0.1-py3.7.egg/seroba/serotyping.py", line 453, in _prediction
  File "/usr/local/lib/python3.7/dist-packages/seroba-1.0.1-py3.7.egg/seroba/serotyping.py", line 269, in _find_serotype
  File "/usr/lib/python3/dist-packages/pymummer/nucmer.py", line 144, in run
    syscall.run('bash ' + script, verbose=self.verbose)
  File "/usr/lib/python3/dist-packages/pymummer/syscall.py", line 26, in run
    raise Error('Error running command:', cmd)
pymummer.syscall.Error: ('Error running command:', 'bash run_nucmer.sh')```

Josh

**Comment by eppinglen** [comment]
Hi Josh,

you don't need to provide an assembly as input to SeroBA. An assembly of your serotype is generated during the run. In case of a serotype within a serogroup, NUCmer is used to identify relevant genes and SNPs in order to determine to correct serotype. 

Your Error message indicates that the assembly could not be generated, due to a lack of a sufficient amount of reads. If you like you can share you data with me and I will take a look into it. 

Best 
Lennard

**Comment by tseemann** [comment]
To avoid the locale errors, seroba should run 
```
LC_ALL=C bash seroba
```
instead of just
```
bash seroba
```

**Comment by abcdtree** [comment]
Thanks, Lennard. I think there is some problem with the paired reads. I will close this Issue.

Josh
