### ISSUE TITLE
KeyError:'24B' 

### ISSUE THREAD

**Issue by km-bit** [sanger-pathogens/seroba#53]
Hey everyone,

I am getting a KeyError when I am running seroba on my test data. 

```
Traceback (most recent call last):
  File "/home/user/.local/bin/seroba", line 86, in <module>
    args.func(args)
  File "/home/user/.local/lib/python3.8/site-packages/seroba/tasks/sero_run.py", line 19, in run
    sero.run()
  File "/home/user/.local/lib/python3.8/site-packages/seroba/serotyping.py", line 479, in run
    cluster = self.serotype_cluster_dict[self.best_serotype]
KeyError: '24B'
```
I am not sure what it means or how to fix it.  Maybe someone had the same or a similar problem ?

Thank you in advance!

**Comment by eppinglen** [comment]
Hi,

which Version of SeroBA are you using? Did you downloaded the database from this git repository or did you used the build in function of SeroBA?

**Comment by km-bit** [comment]
Hey Lennard,

The version is 1.0.0 and I downloaded the database from the git repository.  But I think the error handled itself, because yesterday my system crashed and after reinstalling seroba again from source it cannot find the command seroba. I guess I have to figure that out first.

But thank you for the quick response!

Karsten

**Comment by eppinglen** [comment]
The latest version of ARIBA (prepareref) seems to create an odd output of the cdhit_cluster.tsv. This leads to problems with the prediction for some serotypes. 
The current solution would be to downgrade ARIBA (e.g. version 2.11.1).  Afterwards the database has to be rebuild.
