### ISSUE TITLE
Default for runSerotyping coverage not being set correctly

### ISSUE THREAD

**Issue by AdmiralenOla** [sanger-pathogens/seroba#57]
Dear seroba team,

I have run into an issue where serotyping won't run unless I explicitly set coverage.

```
root@d2d570a8775d:/# seroba runSerotyping seroba/database/ data/testsample_1.fastq.gz data/testsample_2.fastq.gz data/TESTcontainer
Traceback (most recent call last):
  File "/usr/local/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==1.0.2', 'seroba')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/EGG-INFO/scripts/seroba", line 86, in <module>
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/seroba/tasks/sero_run.py", line 13, in run
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/seroba/serotyping.py", line 34, in __init__
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```
It seems like a default value for cov is not being set? I can get it to run by explicitly specifying coverage:
```
root@d2d570a8775d:/# seroba runSerotyping --coverage 20 /seroba/database/ /data/ERR1438805_1.fastq.gz /data/ERR1438805_2.fastq.gz /data/TESTcontainer
```
I am using the latest docker container from sangerpathogens/seroba (b4f4e60ee092)

**Comment by sreerampeela** [comment]
Even I am facing the same error. I am running singularity container on centos7 shared compute resources
