### ISSUE TITLE
Got an error massage through docker with Ubuntu20.04 LTS

### ISSUE THREAD

**Issue by snakano0527** [sanger-pathogens/seroba#58]
When I run seroBA using docker 20.10.1 in Ubuntu20.04LTS, I got an error massage as follows,

Traceback (most recent call last):
  File "/usr/local/bin/seroba", line 4, in <module>
    __import__('pkg_resources').run_script('seroba==1.0.2', 'seroba')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/EGG-INFO/scripts/seroba", line 86, in <module>
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/seroba/tasks/sero_run.py", line 13, in run
  File "/usr/local/lib/python3.8/dist-packages/seroba-1.0.2-py3.8.egg/seroba/serotyping.py", line 34, in __init__
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

How can I solve this problem?

**Comment by sreerampeela** [comment]
Hi..any suggestions on how this error was resolved for you?
