### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by lexleong** [sanger-pathogens/seroba#67]
Hi,
I have been using seroba v1.0.1 recently, but after changing to seroba v.1.0.2, i started having the same error of min memory must be at least 2GB. The same thing happened to me even after reverting back to v.1.0.1...

```
Error: Wrong parameret: min memory must be at least 2GB
/phe/tools/miniconda3/envs/phetype/bin/kmc_tools simple /scratch/iidlleo/Spneumoniae/temp.kmctmwj04if/2212515304 /phe/tools/seroba/database/kmer_db/35B/35B intersect /scratch/iidlleo/Spneumoniae/temp.kmctmwj04if/inter
Error: Cannot open file /scratch/iidlleo/Spneumoniae/temp.kmctmwj04if/2212515304.kmc_pre
Error: Cannot open file /scratch/iidlleo/Spneumoniae/temp.kmctmwj04if/inter.kmc_pre
Traceback (most recent call last):
  File "/phe/tools/miniconda3/envs/phetype/bin/seroba", line 86, in <module>
    args.func(args)
  File "/phe/tools/miniconda3/envs/phetype/lib/python3.6/site-packages/seroba/tasks/sero_run.py", line 19, in run
    sero.run()
  File "/phe/tools/miniconda3/envs/phetype/lib/python3.6/site-packages/seroba/serotyping.py", line 468, in run
    self._run_kmc()
  File "/phe/tools/miniconda3/envs/phetype/lib/python3.6/site-packages/seroba/serotyping.py", line 68, in _run_kmc
    with open( temp_hist, 'r') as fobj:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/iidlleo/Spneumoniae/temp.kmctmwj04if/hist'

```
Is there something missing in my dependencies?

**Comment by cfsancas** [comment]
I solve a similar issiu downgrading kmc version
```sh
conda install kmc=3.1.2
```
