### ISSUE TITLE
errors during installation via conda/mamba

### ISSUE THREAD

**Issue by ulrichmarkus** [sanger-pathogens/seroba#78]
Dear Lennard,

is the tool seroba still maintained?
We had issues with the installation via conda and mamba.

#Standard installation from readme.md
`conda install -c bioconda seroba`
--> error with incompatible glibc versions.

#Standard installation from [bioconda](http://bioconda.github.io/recipes/seroba/README.html)
`mamba install seroba`
--> seroba does not exist

> Could not solve for environment specs
The following package could not be installed
└─ seroba does not exist (perhaps a typo or a missing channel).

#Installation with custom yml file with information from this [post](https://github.com/sanger-pathogens/seroba/issues/61#issuecomment-1060883390)
`#conda
conda env create -f seroba.yml`
--> worked, but after setting up [databases](https://github.com/sanger-pathogens/seroba#usage), we got this error:

> ERROR: I tried to get the version of nucmer with: "[/mnt/localdata/homes/user/miniconda3/envs/seroba/bin/nucmer --version](mailto:/mnt/localdata/homes/user/miniconda3/envs/seroba/bin/nucmer%20--version)" and the output didn't match this regular expression: "^NUCmer \(NUCleotide MUMmer\) version ([0-9\.]+)" 
Something wrong with at least one dependency. Please see the above error message(s)
Traceback (most recent call last):
  File "[/mnt/localdata/homes/user/miniconda3/envs/seroba/bin/seroba](mailto:/mnt/localdata/homes/mul21@helmholtz-hzi.de/miniconda3/envs/seroba/bin/seroba)", line 3, in <module>
    import seroba
  File "[/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/__init__.py](mailto:/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/__init__.py)", line 16, in <module>
    from seroba import *
  File "[/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/kmc.py](mailto:/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/kmc.py)", line 6, in <module>
    ext_progs = external_progs.ExternalProgs()
  File "[/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/external_progs.py](mailto:/mnt/localdata/homes/user/miniconda3/envs/seroba/lib/python3.6/site-packages/seroba/external_progs.py)", line 90, in __init__
    raise Error('Dependency error(s). Cannot continue')

We then removed  line 15 and 27 in the [script external_progs.py](https://github.com/sanger-pathogens/seroba/blob/master/seroba/external_progs.py).

Now we can call seroba but not sure if it really works now.

Thanks for your time and input on this topic!

All the best,
Markus

**Comment by emmagraffice** [comment]
Having the same issue. Have you found any solutions?

**Comment by ulrichmarkus** [comment]
no we dropped this tool and found another way to analyse our data without using seroba. but if it is possible for you, maybe just pull the docker container. if this is build with the original tools and dependencies then it should work just fine...
